session_name: ${PROJECT_NAME}
start_directory: ./
windows:
    - window_name: dev
      focus: True
      layout: main-horizontal
      panes:
          - shell_command:
              - source /env/bin/activate
              - cd ./app
              - nvim .
          - shell_command:
              - source /env/bin/activate
              - cd ./tests
              - nvim .
          - shell_command:
              - source /env/bin/activate
              - ipython
              - clear
